# Generated by Django 4.0.4 on 2022-04-17 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('환불', '환불'), ('반품', '반품'), ('사이즈 교환', '사이즈 교환'), ('배송지 변경', '배송지 변경')], max_length=10, verbose_name='카테고리')),
                ('subject', models.CharField(max_length=50, verbose_name='제목')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일')),
                ('email_receive', models.BooleanField(default=False)),
                ('message', models.CharField(blank=True, max_length=500, null=True, verbose_name='문자')),
                ('message_receive', models.BooleanField(default=False)),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('reference', models.URLField(verbose_name='site_url')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('final_modify_date', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('final_modifier', models.CharField(blank=True, max_length=20, null=True, verbose_name='최종수정자')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
