# Generated by Django 4.0.4 on 2022-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='reference',
            field=models.URLField(blank=True, null=True, verbose_name='site_url'),
        ),
    ]
