# Generated by Django 4.0.4 on 2022-05-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.TextField(choices=[('1', '문의 등록'), ('2', '접수 완료'), ('3', '답변 완료')], default=1, max_length=3, verbose_name='상태'),
            preserve_default=False,
        ),
    ]
