# Generated by Django 4.0.4 on 2022-04-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일시'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='final_modify_date',
            field=models.DateTimeField(auto_now=True, verbose_name='최종 수정일시'),
        ),
    ]
