# Generated by Django 4.0.4 on 2022-04-17 09:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_faq_create_date_alter_faq_final_modify_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='final_modifier',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=10, verbose_name='최종수정자'),
        ),
    ]
