# Generated by Django 4.0.4 on 2022-04-17 09:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_alter_faq_final_modifier_alter_faq_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='final_modifier',
            field=models.CharField(blank=True, default=django.contrib.auth.models.User, max_length=10, null=True, verbose_name='최종수정자'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
